### ISSUE TITLE
Can I use the model for gaze estimation only?

### ISSUE THREAD

**Issue by pourfard** [joonb14/GAZEL#1]
Hello and thanks for sharing the models. 
I was looking for something like eye tracking for everyone on mobile devices. I want to know that if the user eyes are looking outside of the screen or not (looking inside of the screen) and don't need the exact looking point. Can I do something like this without calibration phase and fixed parameters or calibration phase is always necessary?

**Comment by joonb14** [comment]
My repository is for research purposes, and my approach is building a personalized model. So if you are trying to provide the solution that works for everyone, you should look at https://seeso.io/ 
Their solution will be suitable for your purpose! 
Look at their APIs and Android sample application: https://github.com/visualcamp/SeeSoSample-Android
