### ISSUE TITLE
Can not calib

### ISSUE THREAD

**Issue by sunzhe09** [joonb14/GAZEL#2]
when i click the calib button ，My smartphone don't have responce ，just a black screen

**Comment by joonb14** [comment]
Thank you for submitting issue! 
Before checking our code, I want to ask you about several things. Have you followed the instructions on the README? We didn't provide the pretrained gaze tracker model, so before anything you need to train your generalized gazetracker using the gaze data collected from [MLKitGazeDataCollectingButton](https://github.com/joonb14/MLKitGazeDataCollectingButton). After this process you need to convert it to TFLite model then put your TFLite model in the "GAZEL/GazeTracker/app/src/main/assets/custom_models/eval/" directory. Then follow the [issues](https://github.com/joonb14/GAZEL#issues). 
Thank you!
